#!/usr/bin/python3

"""
Contains RectangleTest class
"""


import unittest
from models.rectangle import Rectangle


class RectangleTest(unittest.TestCase):
    """ Testing Rectangle Class """
    def test_cannot_initialize_with_zero_arguments(self):
        """ check if Rectangle is properly initialized """
        with self.assertRaises(TypeError) as ctx:
            Rectangle()

    def test_cannot_initialize_with_one_argument(self):
        """ check if Rectangle is properly initialized """
        with self.assertRaises(TypeError) as ctx:
            Rectangle(1)

    def test_can_initialize_with_two_or_more_arguments(self):
        """ check if Rectangle is properly initialized """
        rectangle = Rectangle(1, 2, id=10)
        self.assertGreater(rectangle.id, 10)



